#ifndef _OSD_MESSAGE_H_
#define _OSD_MESSAGE_H_

// 滚动字幕信息

enum MESSAGE_TYPE // 消息类型
{
	MESSAGE_NOTICE		= 1, // 公告
	MESSAGE_BLESSING	= 2, // 祝福词
	MESSAGE_FOUND_SOME_ONE	= 3, // 寻人启事
	MESSAGE_PAY_REMANDING	= 4, // 结帐预告
	MESSAGE_SERVICE_ANSWER	= 5, // 服务响应
	MESSAGE_FIRE_ALARM	= 6, // 火警
	MESSAGE_ROBBER_ALARM	= 7, // 匪警
};

enum MESSAGE_SHOW_MODE // 消息显示方式
{
	MESSAGE_SHOW_NONE	= 0, // 不显示
	MESSAGE_SHOW_COMPUTER	= 1, // 在电脑上显示
	MESSAGE_SHOW_TV		= 2, // 在电视上显示
	MESSAGE_SHOW_BOTH	= 3, // 同时在电脑和电视上显示
};

enum MESSAGE_CONTENT_TYPE // 消息内容类型
{
	MESSAGE_NONE	= 0, // 无
	MESSAGE_TEXT	= 1, // 文字
	MESSAGE_PICTURE	= 2, // 图片
	MESSAGE_BOTH	= 3, // 图片和文字
	MESSAGE_MPG     = 4, // 视频
	MESSAGE_MPG_BOTH= 5, // 视频和文字
};

enum OSD_SHOW_CONTENT
{
	CONTROL_OSD__NONE		= 0,	// 无

	CONTROL_OSD__PAUSE,	// 暂停
	CONTROL_OSD__NEXT,	// 下一首
	CONTROL_OSD__CHANNEL_KALAOK,	// 原唱
	CONTROL_OSD__CHANNEL_ACCOMPANY,    //伴唱
	CONTROL_OSD__RECORD,	// 录音中……
	CONTROL_OSD__PLAYBACK,	// 回放中……
	CONTROL_OSD__VOLUME_UP,	// 音乐音量+
	CONTROL_OSD__VOLUME_DOWN, //音乐音量-
	CONTROL_OSD__VOLUME_MUTE,  //静音

    CONTROL_OSD__MICROPHONE_VOLUME_UP,   // 麦克风音量加
	CONTROL_OSD__MICROPHONE_VOLUME_DOWN,   // 麦克风音量减

	CONTROL_OSD__TUNE_UP,       // 音调加
	CONTROL_OSD__TUNE_DOWN,     // 音调减
	CONTROL_OSD__TUNE_ORIGINAL, //原调

	CONTROL_OSD__SERVICE,	// 服务

	CONTROL_OSD__ENTER_AUTO_SONG,	// 进入导唱
	CONTROL_OSD__EXIT_AUTO_SONG,	// 退出导唱


	//音效
	CONTROL_OSD_AUDIO_EFFECT_STANDARD, //标准
	CONTROL_OSD_AUDIO_EFFECT_THEATER, //剧场
	CONTROL_OSD_AUDIO_EFFECT_PROFESSIONAL, //唱将
	CONTROL_OSD_AUDIO_EFFECT_MAGIC, //魔音
	CONTROL_OSD_AUDIO_EFFECT_RESERVE1,  //K歌
	CONTROL_OSD_AUDIO_EFFECT_RESERVE2, //通俗
	CONTROL_OSD_AUDIO_EFFECT_RESERVE3,
	CONTROL_OSD_AUDIO_EFFECT_RESERVE4,

	//气氛
	CONTROL_OSD_ATMOSPHERE_APPLAUSE, //鼓掌
	CONTROL_OSD_ATMOSPHERE_CHEER,       //欢呼
	CONTROL_OSD_ATMOSPHERE_OUTCRY,      //催眠
	CONTROL_OSD_ATMOSPHERE_WHISTLE,     //狂汗

	//灯光
	CONTROL_OSD_LIGHT_STANDARD,             //灯光 标准
	CONTROL_OSD_LIGHT__BACKGROUND,           //灯光 背景
	CONTROL_OSD_LIGHT__STAGE,                //灯光 舞台
	CONTROL_OSD_LIGHT__SCINTILLATION,        //灯光 屏闪
	CONTROL_OSD_LIGHT_CLOSE,                //灯光 关闭
	CONTROL_OSD_LIGHT_OPEN,                 //灯光 开
	CONTROL_OSD_LIGHT1,                     //灯光1
	CONTROL_OSD_LIGHT2,                     //灯光2
	CONTROL_OSD_LIGHT3,                     //灯光3
	CONTROL_OSD_LIGHT4,                     //灯光4
	CONTROL_OSD_LIGHT5,                     //灯光5
	CONTROL_OSD_LIGHT6,                     //灯光6
	CONTROL_OSD_LIGHT7,                     //灯光7
	CONTROL_OSD_LIGHT8,                     //灯光8

	//环境音
	CONTROL_OSD_ENVIRONMENT_AUDIO_MEETING,   //会议
	CONTROL_OSD_ENVIRONMENT_AUDIO_AIRPORT,   //飞机场
	CONTROL_OSD_ENVIRONMENT_AUDIO_ROAD,      //马路上
	CONTROL_OSD_ENVIRONMENT_AUDIO_STATION,   //火车站
	CONTROL_OSD_ENVIRONMENT_AUDIO_MAHJONG,   //麻将中
	CONTROL_OSD_ENVIRONMENT_AUDIO_RAIN,      //下雨中

	//混响
	CONTROL_OSD_REVERBERATION_DOWN,        //混响减
	CONTROL_OSD_REVERBERATION_UP,          //混响加

	//空调
	CONTROL_OSD_AIR_CONDITION_STRONG,          //空调强
	CONTROL_OSD_AIR_CONDITION_MID,          //空调中
	CONTROL_OSD_AIR_CONDITION_WEAK,          //空调弱
	CONTROL_OSD_AIR_CONDITION_TEMPERATURE_UP,     //温度+
	CONTROL_OSD_AIR_CONDITION_TEMPERATURE_DOWN,   //温度-
	CONTROL_OSD_AIR_CONDITION_CLOSE,          //空调关闭
	CONTROL_OSD_DISCHARGE_AIR_FUNCTION,          //排风
	CONTROL_OSD_DISCHARGE_AIR_CLOSE,             //排风关闭
	CONTROL_OSD_AIR_CONDITION_REFRIGERATION,      //制冷
	CONTROL_OSD_AIR_CONDITION_HEATING,          //制热

	//评分
	CONTROL_OSD_SCORE_OPEN,                  //打开评分
	CONTROL_OSD_SCORE_CLOSE,                 //关闭评分

	//新音效
	CONTROL_OSD_AUDIO_EFFECT,				//自动

	CONTROL_OSD_ATMOSPHERE_HAOZAN, //好赞
	CONTROL_OSD_ATMOSPHERE_SHIHUA, //石化
	CONTROL_OSD_ATMOSPHERE_XIANHUA, //鲜花
	CONTROL_OSD_ATMOSPHERE_TUXIE, //吐血
	CONTROL_OSD_ATMOSPHERE_FEIWEN, //飞吻
	CONTROL_OSD_ATMOSPHERE_XINSUI, //心碎
	CONTROL_OSD_ATMOSPHERE_HAIXIU, //害羞
	CONTROL_OSD_ATMOSPHERE_ZADAN, //砸蛋

	//音效
	CONTROL_OSD_MUSIC_SOUND_STANDARD, //音乐音效标准
	CONTROL_OSD_MUSIC_SOUND_THEATER, //音乐音效剧场
	CONTROL_OSD_MUSIC_SOUND_PROFESSIONAL, //音乐音效唱将
	CONTROL_OSD_MUSIC_SOUND_MAGIC, //音乐音效魔音
	CONTROL_OSD_MUSIC_SOUND_RESERVE1, //音乐音效魔音
};

//屏幕显示的Flash动画
enum SCREEN_FLASH_TYPE
{
	SCREEN_FLASH_APPLAUSE = 0,			//鼓掌
	SCREEN_FLASH_CHEER,					//欢呼
	SCREEN_FLASH_OUTCRY,				//催眠
	SCREEN_FLASH_WHISTLE,				//狂汗
	SCREEN_FLASH_HAOZAN,				//好赞
	SCREEN_FLASH_SHIHUA,				//石化
	SCREEN_FLASH_XIANHUA,				//鲜花
	SCREEN_FLASH_TUXIE,					//吐血
	SCREEN_FLASH_FEIWEN,				//飞吻
	SCREEN_FLASH_XINSUI,				//心碎
	SCREEN_FLASH_HAIXIU,				//害羞
	SCREEN_FLASH_ZADAN,					//砸蛋
};

#endif