#ifndef _SONG_VARIABLE_H_
#define _SONG_VARIABLE_H_


//目前页允许显示的最大行数
#define PAGE_SHOW_MAX_ROW_COUNT 50
#define HANDHELD_PAGE_SHOW_ROW_COUNT  8 //手持

//歌曲显示的页数
#define SCREEN_SHOW_PAGE_COUNT 3
#define RECORDER_SHOW_PAGE_COUNT  200 //录音页面显示的页数

//测机使用
#define TEST_PAGE_SHOW_ROW_COUNT    10
#define TEST_SCREEN_SHOW_PAGE_COUNT 1

// 歌曲语种
enum SONG_LANGUAGE
{
	SONG_LANGUAGE_ALL	    	= 0,    //全部
	SONG_LANGUAGE_CHINESE		= 1,	//国语
	SONG_LANGUAGE_YUE	    	= 2,	//粤语
	SONG_LANGUAGE_MINNAN		= 3,	//闽南语
	SONG_LANGUAGE_ENGLISH		= 4,	//英语
	SONG_LANGUAGE_KOREAN		= 5,	//韩语
	SONG_LANGUAGE_JAPANESE		= 6,	//日语
	SONG_LANGUAGE_OTHERS        = 7,    //其他
	SONG_LANGUAGE_THAI          = 8,    //泰语
	SONG_LANGUAGE_MONGOLIA      = 9,    //蒙语
	SONG_LANGUAGE_RUSSIAN       = 10,   //俄语
	SONG_LANGUAGE_ZHUYIN        = 10,   //繁体注音
#ifdef DON_GUAN_K_PLUS
	SONG_SLOW_ROLL        = 11,   //慢摇
#endif // DON_GUAN_K_PLUS
};


// 歌曲版本
enum SONG_VERSION
{
	SONG_VERSION_UNKNOWN=0,
	SONG_VERSION_CONCERT,	// 演唱会
	SONG_VERSION_ENJOY,     //欣赏版
	SONG_VERSION_MTV,	// MTV
	SONG_VERSION_VIEW,	// 风景
	SONG_VERSION_STORY,	// 故事情节
	SONG_VERSION_PERSON,	// 人物
	SONG_VERSION_MOVIE,     //影视版
	SONG_VERSION_DJ,		//迪曲
	SONG_VERSION_DANCE,   //舞曲
	SONG_VERSION_VCD,   //VCD
	SONG_VERSION_DVD,    //DVD
	SONG_VERSION_HD,     //HD
	SONG_VERSION_BAIDU, //百度音乐
	SONG_VERSION_QQ,	//QQ音乐
	SONG_VERSION_KUGOU, //酷狗音乐
	SONG_VERSION_KUWO,  //酷我音乐
	SONG_VERSION_TREND_LIST,	//潮流榜单
};


//////////////////////////////////////////////////////////////////////////
// 歌曲格式

enum SONG_FORMAT
{
	SONG_FORMAT_UNKNOWN	= 0,
	SONG_FORMAT_MPEG_1	= 1,	// MPEG-1
	SONG_FORMAT_MPEG_2	= 2,	// MPEG-2
};

//符合条件的有多少页数据
enum PAGE_FLAG
{
	NO_PAGE=0,        //没有查询到符合条件的数据
	ONE_PAGE,         //只有一页数据
	TWO_PAGE,         //两页数据
	THREE_PAGE,       //三页数据
};

//播放器的播放状态
enum PLAYER_PLAY_STATE
{
	BEGIN_STATE,     //开始
	END_STATE,       //结束
	IDLESSE_STATE,   //空闲
    PLAY_SONG_STATE, //播放用户点的歌
	PLAY_DJ_STATE,   //播放DJ
	TEST_SONG_STATE, //测试歌曲状态 和屏切的预览一样
};

enum SHOW_SONG_LIST_TYPE
{
	SHOW_SELECT_SONG,   //已选歌曲
	SHOW_SING_SONG,     //已唱歌曲

};

//混合音频的类型
enum WAVE_MIXER_AUDIO_TYPE
{
	//码值要修改，也要相应的修改enum FLASH_SEND_FUNCTION_CODE  相差1000
	WAVE_ATMOSPHERE_APPLAUSE    =1160,  //鼓掌
	WAVE_ATMOSPHERE_CHEER       =1161,  //欢呼
	WAVE_ATMOSPHERE_OUTCRY      =1162,  //催眠
	WAVE_ATMOSPHERE_WHISTLE     =1163,  //狂汗


	WAVE_ATMOSPHERE_DRUM_KIT_LEFT_FRUM1   =1220,   //左一鼓
	WAVE_ATMOSPHERE_DRUM_KIT_LEFT_FRUM2   =1221,   //左二鼓
	WAVE_ATMOSPHERE_DRUM_KIT_MIDDLE_FRUM  =1222,   //中间的鼓
	WAVE_ATMOSPHERE_DRUM_KIT_RIGHT_FRUM2  =1223,   //右二鼓
	WAVE_ATMOSPHERE_DRUM_KIT_RIGHT_FRUM1  =1224,   //右一鼓
	WAVE_ATMOSPHERE_DRUM_KIT_PRE_FRUM     =1225,   //前大鼓
	WAVE_ATMOSPHERE_DRUM_KIT_LEFT_CYMBAL1 =1226,   //左一镲
	WAVE_ATMOSPHERE_DRUM_KIT_LEFT_CYMBAL2 =1227,   //左二镲
	WAVE_ATMOSPHERE_DRUM_KIT_RIGHT_CYMBAL2=1228,   //右二镲
	WAVE_ATMOSPHERE_DRUM_KIT_RIGHT_CYMBAL1=1229,   //右一镲

	WAVE_ATMOSPHERE_PIANO_BLACK1 =1330,            //钢琴黑键（左起，共15个）
	WAVE_ATMOSPHERE_PIANO_BLACK2 =1331,
	WAVE_ATMOSPHERE_PIANO_BLACK3 =1332,
	WAVE_ATMOSPHERE_PIANO_BLACK4 =1333,
	WAVE_ATMOSPHERE_PIANO_BLACK5 =1334,
	WAVE_ATMOSPHERE_PIANO_BLACK6 =1335,
	WAVE_ATMOSPHERE_PIANO_BLACK7 =1336,
	WAVE_ATMOSPHERE_PIANO_BLACK8 =1337,
	WAVE_ATMOSPHERE_PIANO_BLACK9 =1338,
	WAVE_ATMOSPHERE_PIANO_BLACK10=1339,
	WAVE_ATMOSPHERE_PIANO_BLACK11=1340,
	WAVE_ATMOSPHERE_PIANO_BLACK12=1341,
	WAVE_ATMOSPHERE_PIANO_BLACK13=1342,
	WAVE_ATMOSPHERE_PIANO_BLACK14=1343,
	WAVE_ATMOSPHERE_PIANO_BLACK15=1344,

	WAVE_ATMOSPHERE_PIANO_WHITE1 =1345, //钢琴白键（左起，共21个）
	WAVE_ATMOSPHERE_PIANO_WHITE2 =1346,
	WAVE_ATMOSPHERE_PIANO_WHITE3 =1347,
	WAVE_ATMOSPHERE_PIANO_WHITE4 =1348,
	WAVE_ATMOSPHERE_PIANO_WHITE5 =1349,
	WAVE_ATMOSPHERE_PIANO_WHITE6 =1350,
	WAVE_ATMOSPHERE_PIANO_WHITE7 =1351,
	WAVE_ATMOSPHERE_PIANO_WHITE8 =1352,
	WAVE_ATMOSPHERE_PIANO_WHITE9 =1353,
	WAVE_ATMOSPHERE_PIANO_WHITE10=1354,
	WAVE_ATMOSPHERE_PIANO_WHITE11=1355,
	WAVE_ATMOSPHERE_PIANO_WHITE12=1356,
	WAVE_ATMOSPHERE_PIANO_WHITE13=1357,
	WAVE_ATMOSPHERE_PIANO_WHITE14=1358,
	WAVE_ATMOSPHERE_PIANO_WHITE15=1359,
	WAVE_ATMOSPHERE_PIANO_WHITE16=1360,
	WAVE_ATMOSPHERE_PIANO_WHITE17=1361,
	WAVE_ATMOSPHERE_PIANO_WHITE18=1362,
	WAVE_ATMOSPHERE_PIANO_WHITE19=1363,
	WAVE_ATMOSPHERE_PIANO_WHITE20=1364,
	WAVE_ATMOSPHERE_PIANO_WHITE21=1365,
	WAVE_ATMOSPHERE_MARACAS      =1390,         //沙锤
	WAVE_ATMOSPHERE_HANDBELL     =1391,         //手铃
	WAVE_ATMOSPHERE_DRUM         =1392,         //鼓

	WAVE_ATMOSPHERE_HAOZAN = 1531, //好赞
	WAVE_ATMOSPHERE_SHIHUA = 1532, //石化
	WAVE_ATMOSPHERE_XIANHUA = 1533,//鲜花
	WAVE_ATMOSPHERE_TUXIE = 1534,//吐血
	WAVE_ATMOSPHERE_FEIWEN = 1535,//飞吻
	WAVE_ATMOSPHERE_XINSUI = 1536,//心碎
	WAVE_ATMOSPHERE_HAIXIU = 1537,//害羞
	WAVE_ATMOSPHERE_ZADAN = 1538,//砸蛋
};

//选择的视频的类型
enum PLAY_SONG_TYPE
{
	PLAY_SONG_TYPE_SELECT_SONG,  //选择的正常播放的歌曲
	PLAY_SONG_TYPE_RECORDER_SONG,//录的歌曲
	PLAY_SONG_TYPE_IDLESSE,      //空闲歌曲
	PLAY_MOVIE,                  //电影
	PLAY_GAME,                   //游戏
	PLAY_MSG_VIDEO,              //消息系统发送过来，要求播放的视频
	PLAY_MSG_VIDEO_FIRE_ALARYM,  //消息发送过来的火警视频
	PLAY_U_DISK_SONG,            //播放U盘歌曲
	PLAY_LOBBY_LIVE,             //播放大厅直播
	PLAY_TV,                     //播放电视
	PLAY_SCORE_VIDEO,            //分数视频
	PLAY_MUSIC_ENJOY,			 //音乐欣赏歌曲
	PLAY_DLNA_VIDEO,			 //DLNA功能的视频
	PLAY_TREND_LIST,			 //潮流榜单
};

#endif